version: 1
labels:
  - label: 'feature'
    bracnh: '^feature/.*'
  - label: 'bugfix'
    bracnh: '^bugfix/.*'
  - label: 'style'
    bracnh: '^style/.*'
  - label: 'refactoring'
    bracnh: '^refactoring/.*'
  - label: 'PRD'
    bracnh: '^prd/v[0-9]+[.][0-9]+'
