name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, mrx-runner-desktop]

    strategy:
      matrix:
        node-version: [ 12.x, 14.x, 16.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm ci
          npm run lint:check
          npm run stylelint:check
          npm run build
          npm run start & npx wait-on http://localhost:3000
        # 추후 test command 추가

  docker-build:
    runs-on: [self-hosted, mrx-runner-desktop]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Setup Buildx
        # You may pin to the exact commit or the version.
        uses: docker/setup-buildx-action@v1.5.0

      - name: Docker Build
        uses: docker/build-push-action@v2.6.1
        with:
          push: false
          # Build's context is the set of files located in the specified PATH or URL
          context: ./
          # Path to the Dockerfile
          file: ./docker/Dockerfile

